---
- hosts: localhost
  connection: local

  tasks:
  - name: install apt packages
    apt:
      name:
        - htop
        - terminator
        - httpie
        - exa
        - bat
        - docker.io
        - docker-compose

  - name: install snap packages
    snap:
      name: 
        - nvim
        - node
        - kotlin
        - intellij-idea-community
      classic: yes

  - name: Create Docker group
    group:
      name: docker

  - name: Add docker group to $USER
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: true

  - name: Download Rust installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/rustup.sh
      mode: 0755

  - name: Install Rust
    shell: /tmp/rustup.sh -y

  - name: Setup git prompt
    git:
      repo: 'https://github.com/magicmonty/bash-git-prompt.git'
      dest: /home/{{ ansible_user_id }}/.bash-git-prompt
      depth: 1
    become: true

  - name: Complete basic .bashrc
    blockinfile:
      path: /home/{{ ansible_user_id }}/.bashrc
      block: |
        export EDITOR=nvim
        alias vim=nvim
        alias ls=exa
        alias cat=batcat

        if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
          GIT_PROMPT_ONLY_IN_REPO=1
          source $HOME/.bash-git-prompt/gitprompt.sh
        fi

