---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - terminator
        - httpie

  - name: install snaps
    snap:
      name: 
        - nvim
        - node
        - kotlin
        - intellij-idea-community
      classic: yes

  - name: Install Rust
    shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    args:
      warn: no

