---
- hosts: localhost
  connection: local

  tasks:
  - name: install apt packages
    apt:
      name:
        - htop
        - terminator
        - httpie
        - exa
        - bat
        - ripgrep
        - xclip
        - tree
        - g++
        - docker.io
        - docker-compose
    become: true

  - name: install snap packages
    snap:
      name: 
        - nvim
        # - node // todo: install it from source
        - kotlin
        - intellij-idea-community
        - webstorm
        - android-studio
        - brave
        - slack
      classic: yes
    become: true

  - name: Create Docker group
    group:
      name: docker
    become: true

  - name: Add docker group to $USER
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: true

  - name: Download Rust installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/rustup.sh
      mode: 0755
    become: true

  - name: Install Rust
    shell: /tmp/rustup.sh -y

  - name: Download node 16.13.1
    get_url:
      url: https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x64.tar.xz
      dest: /tmp/node-v16.13.1-linux-x64.tar.xz
      mode: 0755
    become: true

  - name: Extract node 16.13.1
    unarchive:
      src: /tmp/node-v16.13.1-linux-x64.tar.xz
      dest: /etc
    become: true

  - name: Setup git prompt
    git:
      repo: 'https://github.com/magicmonty/bash-git-prompt.git'
      dest: /home/{{ ansible_user_id }}/.bash-git-prompt
      depth: 1
    become: true

  - name: Complete basic .bashrc
    blockinfile:
      path: /home/{{ ansible_user_id }}/.bashrc
      block: |
        export EDITOR=nvim
        alias vim=nvim
        alias ls=exa
        alias cat=batcat

        if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
          GIT_PROMPT_ONLY_IN_REPO=1
          source $HOME/.bash-git-prompt/gitprompt.sh
        fi

        export PATH=$PATH:/etc/node-v16.13.1-linux-x64/bin

  - name: Clone my vim config
    git:
      repo: git@github.com:ibado/myvimrc.git
      dest: /home/{{ ansible_user_id }}/.myvimrc

  - name: Setup my vim config
    shell: |
      mkdir -p /home/{{ ansible_user_id }}/.config/nvim/
      ln -s /home/{{ ansible_user_id }}/.myvimrc/init.vim /home/{{ ansible_user_id }}/.config/nvim/init.vim
      curl -fLo /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    args:
      warn: no
