---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - terminator

  - name: install rust
    shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

  - name: install snaps
    snap:
      name: 
        - nvim
        - node
        - kotlin
      classic: yes

